version: "3.9"

services:
  db:
    image: postgres:15
    container_name: interview-db
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview -d interview_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: interview-backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: interview-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  agent:
    build: ./agent
    container_name: interview-agent
    env_file:
      - ./agent/.env
    depends_on:
      - backend
    volumes:
      - ./agent:/app

volumes:
  db_data: